modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "vonixcore"
version = "${version}"
displayName = "VonixCore"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.vonixcore]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vonixcore]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vonixcore]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "vonixcore.mixins.json"
