modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "vonixcore"
version = "${version}"
displayName = "VonixCore"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.vonixcore]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vonixcore]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vonixcore]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"
